### ISSUE TITLE
HOW to get c connection back on ngrok

### ISSUE THREAD

**Issue by ayushjkl** [karma9874/AndroRAT#118]
![image](https://user-images.githubusercontent.com/98699440/151704730-0f3d08ed-da91-4fe9-ad15-6764d81e0c16.png)

**Comment by Ragi42DEV** [comment]
Bro, you have to start your ngrok server with ./ngrok tcp {port that you are going to use} and in that command that you posted you will use ip 0.0.0.0 and the port that you used to run ngrok server.

**Comment by Enigma1309** [comment]
hey there you have to buy ngrok premium service to get the same webhost back

or you can try any other services like 
 portmap.io (best)
 or pagekite ,etc


ngrok always rests the link , after you kill the session ( i.e. Power off device)


for handling this situation we use a static ip (Not Recommended)
since static ip has a lot more chances to get caught by cyberattackers or even cyber police

hence my personal favorite is portmap.io which always works without any port forwarding or static ip

for more info you can search YouTube or even hackers forum you will get full info there

have a nice day :)

**Comment by Enigma1309** [comment]
> ![image](https://user-images.githubusercontent.com/98699440/151704730-0f3d08ed-da91-4fe9-ad15-6764d81e0c16.png)

hey there you have to buy ngrok premium service to get the same webhost back

or you can try any other services like
portmap.io (best)
or pagekite ,etc

ngrok always rests the link , after you kill the session ( i.e. Power off device)

for handling this situation we use a static ip (Not Recommended)
since static ip has a lot more chances to get caught by cyberattackers or even cyber police

hence my personal favorite is portmap.io which always works without any port forwarding or static ip

for more info you can search YouTube or even hackers forum you will get full info there

have a nice day :)

**Comment by roshin8** [comment]
> > ![image](https://user-images.githubusercontent.com/98699440/151704730-0f3d08ed-da91-4fe9-ad15-6764d81e0c16.png)
> 
> hey there you have to buy ngrok premium service to get the same webhost back
> 
> or you can try any other services like portmap.io (best) or pagekite ,etc
> 
> ngrok always rests the link , after you kill the session ( i.e. Power off device)
> 
> for handling this situation we use a static ip (Not Recommended) since static ip has a lot more chances to get caught by cyberattackers or even cyber police
> 
> hence my personal favorite is portmap.io which always works without any port forwarding or static ip
> 
> for more info you can search YouTube or even hackers forum you will get full info there
> 
> have a nice day :)

Thank you so much! Using portmap.io worked! Was so close to paying for ngrok haha

**Comment by Enigma1309** [comment]
> > > ![image](https://user-images.githubusercontent.com/98699440/151704730-0f3d08ed-da91-4fe9-ad15-6764d81e0c16.png)
> > 
> > 
> > hey there you have to buy ngrok premium service to get the same webhost back
> > or you can try any other services like portmap.io (best) or pagekite ,etc
> > ngrok always rests the link , after you kill the session ( i.e. Power off device)
> > for handling this situation we use a static ip (Not Recommended) since static ip has a lot more chances to get caught by cyberattackers or even cyber police
> > hence my personal favorite is portmap.io which always works without any port forwarding or static ip
> > for more info you can search YouTube or even hackers forum you will get full info there
> > have a nice day :)
> 
> Thank you so much! Using portmap.io worked! Was so close to paying for ngrok haha

i am so glad that my advice helped you
