### ISSUE TITLE
Not fully persistent

### ISSUE THREAD

**Issue by swagkarna** [karma9874/AndroRAT#2]
I have tested this tool in my honor 8x mobile whose android version is 9.0 i have installed the apk in my mobile i got the session  but when i lock the screen my session was aborted when i try to reconnect i could not get back the session. I have also tested this in my samsung galaxy j2 pro mobile whose android version is 6.0 it working fine even after reboot .Can you give a solution for this

**Comment by karma9874** [comment]
The issue with Honor mobiles is that they use aggressive battery saving algorithms and because of that the app closes, to solve that issue you can manually try turning off the power-saving mode
Try the following:
1. Open the Phone Manager app.
2. Tap the Battery icon > Launch
3. Tap the AndroRAT app (Google Service Framework), set to Manage manually with the Run in background option selected.
4. Then, go to the device’s Settings > Apps & notifications > Apps > Settings > Special access > Ignore battery optimization, tap the  AndroRAT app (Google Service Framework) you’re using and select Allow.
Please let me know if this work

**Comment by swagkarna** [comment]
ok let me try and i will comment you soon

**Comment by swagkarna** [comment]
I have tried what u said but its not working

**Comment by STANISLAVREVA** [comment]
Please I need your help. I was able to host another Android device but the problem am facing is how to reconnect to that same device after my Termux session is aborted? How do I reconnect to a former established connection from my Termux?

**Comment by drweird911** [comment]
Is there is the way to keep connection persistent or maybe make changes in script !

**Comment by ShaneRainPain** [comment]
> Is there is the way to keep connection persistent or maybe make changes in script !

Please assist with this i am having same issue on kali linux, how do you re connect to same session after closing?
